<MyLayout>
	BoxLayout:
		orientation: "vertical"
		size: root.width, root.height
		
		Accordion:
			orientation: 'vertical'

			AccordionItem:
				title: "Panel 1"
				Image:
					source: 'images/aspen1.jpg'
			
			AccordionItem:
				title: "Panel 2"
				Label:
					text: "Panel 2 Text"
					font_size: 32
			AccordionItem:
				title: "Panel 3"
				Image:
					source: 'images/aspen2.png'

			AccordionItem:
				title: "Panel 4"
				Label:
					text: "Panel 4 Text"
					font_size: 32		

		