<MyLayout>
	BoxLayout:
		orientation: "vertical"
		size: root.width, root.height
		
		Carousel:
			direction: "right"

			Image:
				source: "images/aspen1.jpg"
			AsyncImage:
				source: 'https://kivycoder.com/wp-content/uploads/2020/12/accordions-for-kivy-python-kivy.jpg'
			Label:
				text: "Hello World!"	
				font_size: 32
			Image:
				source: "images/aspen2.png"

			Image:
				source: "images/aspen3.jpg"