<MyLayout>
	
	BoxLayout:
		orientation: "vertical"
		size: root.width, root.height
		

		Label:
			markup: True
			font_size: 32
			text: "This is [color=#a12c3c][b]Bold[/b][/color] [font=times]Text[/font] [sup]Up[/sup] and [sub]Down[/sub]"

		
		Label:
			markup: True
			font_size: 32
			text: "This is [size=150][i]Italics[/i][/size] Text"

		Button:
			markup: True
			font_size: 32
			text: "[u]Click[/u] [s]ME[/s]!!"			