<MyLayout>
	slide_text: slider_label
	BoxLayout:
		orientation: "vertical"
		size: root.width, root.height
	
		Label:
			id: slider_label
			text_size: self.size
			halign: "center"
			valign: "middle"
			text: "Slide The Slider"
			font_size:32



		Slider:
			min: 1
			max: 50
			step: 1
			orientation: 'horizontal'
			on_value: root.slide_it(*args)
			# Sends name of slider first and value second

