<MyLayout>
	BoxLayout:
		orientation: "vertical"
		size: root.width, root.height

		Splitter:
			sizable_from: 'bottom'
			Button:
				text: "Hello World 1"
				font_size: 32

		Label:
			text: "This is some text!"
			font_size: 32

		
		Splitter:
			sizable_from: 'top'
			Button:
				text: "Hello World 2"
				font_size: 32

		GridLayout:
			cols:2

			Button: 
				text: "Left"
				font_size: 32

			Splitter:
				sizable_from: 'left'

				Button: 
					text: "Right"
					font_size: 32